---
output: html_document
editor_options: 
  chunk_output_type: console
---

# configuration
```{r}
library(tidyverse)

site  <- "sapone"

smc <- read.csv(glue("smc/{site}_SMC.csv"))

itns <- read.csv(glue("itns/{site}_ITN.csv"))
itn_age <- read.csv(glue("itns/{site}_ITN_age.csv"))
itn_season <- read.csv(glue("itns/{site}_ITN_season.csv"))
nmf <- read.csv(glue("nonmalarial_fevers/nmf_rates_generic.csv"))
cm <- read.csv(glue("case_management/{site}_cm.csv"))
```


```{r}

nmf <- data.frame(age_min=c(0,5,15),
                  nmf=c(0.0082,0.0039,0.0039))

nmf %>% left_join(cm %>% filter(trigger!="NewSevereCase")) -> nmf

itns %>% 
  left_join(itn_age) %>%
  merge(itn_season) %>%
  mutate(tot_usage = coverage*age_usage*season_usage) -> itn_sum

ggplot() +
  geom_point(data=smc %>% mutate(start_day=as.Date(start_day,origin="1960-01-01")), size=2,
             aes(x=start_day,y=coverage, shape="SMC",color="0")) +
  geom_point(data=itn_sum %>% mutate(start_day=as.Date(start_day,origin="1960-01-01")),
             aes(x=start_day+season_time,y=tot_usage,
                              color=factor(as.numeric(age)),shape="ITN"))+
  geom_path(data=itn_sum %>% mutate(start_day=as.Date(start_day,origin="1960-01-01")),
            aes(x=start_day+season_time,y=tot_usage,
                             group=interaction(age,year),
                              color=factor(as.numeric(age))))+
  # geom_line(linewidth=1,data=itn_sum, aes(x=start_day+season_time, y=tot_usage, color=factor(as.numeric(age)),
  #                             group=interaction(year,age),
  #                             linetype="ITN Usage")) +
  geom_step(linewidth=1,data=cm %>% mutate(start_day=as.Date(start_day,origin="1960-01-01")),
            aes(x=start_day,y=coverage,
                                     group=interaction(age_min,trigger),
                                     linetype=trigger,color=factor(age_min))) +
  geom_step(linewidth=1,data=nmf %>% mutate(start_day=as.Date(start_day,origin="1960-01-01")),
            aes(x=start_day,y=coverage*nmf,group=age_min,
                         linetype="Non-Malarial Fever",color=factor(age_min)))+ 
  theme_minimal(base_size=16) +
  theme(legend.position=c(0,1),
        legend.justification = c(-0.1,1.1),
        legend.box="horizontal",
        legend.background = element_rect(fill="white",color="transparent"),
        legend.box.background = element_rect(fill="white",color="transparent"))+
  labs(color=NULL, shape=NULL,linetype=NULL) +
  scale_shape_manual(values=c(21,16)) +
  scale_linetype_manual(values=c(1,2,3)) +
  scale_x_date(breaks = "1 years", date_labels = "%Y", date_minor_breaks = "1 month") +
  scale_y_continuous(breaks=seq(0,1,0.1)) +
  xlab("") +ylab("")
  
```

